### ISSUE TITLE
Only parse valid HTTP methods and ignore others

### ISSUE THREAD

**Issue by lumaxis** [luckymarmot/API-Flow#48]
We are using Swagger in an admittedly unusual way by annotating our `swagger.yaml` with some internal info, e.g. which controller class of our service will handle the request.

This looks something like this:

```yaml
  /somePath:
    x-swagger-router-controller: somePathController
    get:
      description: Returns the some data
```

Now when using the Swagger Importer, it parses `x-swagger-router-controller` as just another HTTP method which us understandable but doesn't make sense in our case.
Would you be open to maybe add either a filtering for e.g. everything that starts with `x-` or maybe simply ignore anything that's not in a valid-HTTP-methods whitelist?
