### ISSUE TITLE
Authorization URL not imported from Swagger

### ISSUE THREAD

**Issue by mittsh** [luckymarmot/API-Flow#94]
I just imported the Swagger file from Instagram (on APIs.guru) and it doesn't set the Authorization URL for me:

![image](https://cloud.githubusercontent.com/assets/1319906/20356997/9a1ddb3e-ac26-11e6-8fa0-fa85402be603.png)

Clearly the Swagger has it:

```yaml
securityDefinitions:
  api_key:
    in: query
    name: access_token
    type: apiKey
  instagram_auth:
    authorizationUrl: 'https://instagram.com/oauth/authorize/'
    flow: implicit
    scopes:
      basic: to read a user's profile info and media (granted by default)
      comments: to post and delete comments on a user's behalf
      follower_list: to read the list of followers and followed-by users
      likes: to like and unlike media on a user's behalf
      public_content: to read any public profile info and media on a user’s behalf
      relationships: to follow and unfollow accounts on a user's behalf
    type: oauth2
```
